# Generated by Django 3.2.6 on 2021-11-07 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='transportation',
            field=models.CharField(choices=[('car', 'car'), ('pub', 'publicTransportation'), ('wal', 'walk'), ('etc', 'others')], max_length=3),
        ),
    ]
