# Generated by Django 3.2.9 on 2021-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='kakao_id',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
