# Generated by Django 3.2.6 on 2021-11-08 11:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import route.models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.folder'),
        ),
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='transportation',
            field=models.CharField(choices=[('car', 'car'), ('pub', 'publicTransportation'), ('wal', 'walk'), ('etc', 'others')], max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='route.folder'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.Post.header_date_upload_to),
        ),
        migrations.RemoveField(
            model_name='post',
            name='season',
        ),
        migrations.AddField(
            model_name='post',
            name='season',
            field=models.CharField(blank=True, choices=[('spr', 'spring'), ('sum', 'summer'), ('aut', 'autumn'), ('win', 'winter')], max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='post',
            name='theme',
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.CharField(blank=True, choices=[('friends', 'withFriends'), ('family', 'withFamily'), ('lover', 'withLovers'), ('alone', 'alone')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.Post.thumbnail_date_upload_to),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.DeleteModel(
            name='PlaceInfo',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
    ]
