# Generated by Django 3.2.9 on 2021-12-05 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_place_kakao_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_list', to='route.post'),
        ),
    ]
