# Generated by Django 3.2.6 on 2021-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_alter_path_transportation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Season',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='Transportation',
        ),
        migrations.RemoveField(
            model_name='place',
            name='place',
        ),
        migrations.AddField(
            model_name='place',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='PlaceInfo',
        ),
    ]
