# Generated by Django 3.2.6 on 2021-11-09 02:49

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('route', '0002_auto_20211108_2022'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
