# Generated by Django 3.2.5 on 2021-11-09 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_auto_20211108_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='place',
            name='info',
            field=models.JSONField(default=dict),
        ),
    ]
