# Generated by Django 3.2.9 on 2021-11-09 13:11

from django.db import migrations, models
import route.models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('route', '0003_alter_post_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='info',
        ),
        migrations.AddField(
            model_name='place',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='homepage',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.Post.header_date_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.Post.thumbnail_date_upload_to, verbose_name='Image'),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
