# Generated by Django 3.2.5 on 2021-11-10 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20211109_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PostInFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.folder')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.post')),
            ],
        ),
        migrations.CreateModel(
            name='PlaceInFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.folder')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.place')),
            ],
        ),
    ]
