# Generated by Django 3.2.6 on 2021-11-09 02:55

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('route', '0004_alter_post_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
