# Generated by Django 3.2.5 on 2021-11-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_auto_20211110_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
