# Generated by Django 3.2.6 on 2021-11-09 11:59

from django.db import migrations, models
import route.models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_alter_post_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='place',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.Post.header_date_upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=route.models.Post.thumbnail_date_upload_to, verbose_name='Image'),
        ),
    ]
