# Generated by Django 3.2.6 on 2021-11-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_auto_20211109_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='info',
            field=models.JSONField(),
        ),
    ]
