# Generated by Django 3.2.5 on 2021-11-03 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profileImage',
            new_name='profile_image',
        ),
    ]
